---

- hosts: all
 
  tasks:

  - name: example copying file with owner and permissions
    copy:
      dest: /var/lib/awx/projects/_8__my_playbooks/test-file.txt
      src: /home/Documents/test-file.txt
      remote_src: yes
