---

- hosts: all
 
  tasks:
  
  - name: example copying file with owner and permissions
    copy:
      dest: /joel/var/lib/awx/projects/playbooks/DocumentsForTest/test-file.txt
      src: ~/home/Documents/test-file.txt
      remote_src: yes  
