---

- hosts: all
 
  tasks:
  
  - name: example copying file with owner and permissions
    copy:
      src: ~/var/lib/awx/projects/playbooks/DocumentsForTest/test-file.txt
      dest: ~/home/Documents/test-file2.txt
      remote_src: no   
