---

- hosts: all
 
  tasks:
  - name: Recursively find /tmp files older than 2 days
    find:
      paths: /home/Documents
      age: 36
      recurse: yes
    
#  - name: example copying file with owner and permissions
#    copy:
#      dest: /var/lib/awx/projects/_8__my_playbooks/test-file.txt
#      src: /home/Documents/test-file.txt
#      remote_src: no    
